# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

import autosequence.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('book_type', models.CharField(choices=[('book', 'Book'), ('video', 'Video')], default='book', max_length=250, verbose_name='Book Type')),
                ('language', models.CharField(choices=[('vie', 'Vietnames'), ('eng', 'English')], default='vie', max_length=250, verbose_name='Language')),
                ('point', models.IntegerField(verbose_name='Point')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.book_directory_path, verbose_name='Image')),
                ('video', models.FileField(blank=True, max_length=1000, null=True, upload_to=core.models.book_directory_path, verbose_name='Video')),
                ('status', django_fsm.FSMField(default='draft', max_length=250, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decription')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Is draft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decription')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('sequence_number', autosequence.fields.AutoSequenceField()),
                ('condition', models.IntegerField(default=0, help_text='Total book must be read to pass this level.', verbose_name='Condition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('content', models.CharField(max_length=255, verbose_name='Content')),
                ('page_number', models.IntegerField(verbose_name='Page number')),
                ('image', models.ImageField(upload_to=core.models.page_book_directory_path, verbose_name='Image')),
                ('audio', models.FileField(blank=True, null=True, upload_to=core.models.page_book_directory_path, verbose_name='Audio')),
                ('timing_mapping', models.FileField(blank=True, null=True, upload_to=core.models.page_book_directory_path, verbose_name='Timing Mapping')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
