# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_optional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name Optional')),
                ('badge_type', models.CharField(choices=[('point', 'Point'), ('time', 'Time'), ('total', 'Total Book')], default='point', max_length=250, verbose_name='Badge Type')),
                ('condition_received', models.CharField(max_length=255, verbose_name='Condition Recieved')),
                ('point_received', models.CharField(max_length=255, verbose_name='Point Recieved')),
                ('image', models.ImageField(upload_to='Badge', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Badge',
            },
        ),
        migrations.CreateModel(
            name='KidBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Kid Badge',
            },
        ),
        migrations.CreateModel(
            name='TimesReadBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('last_readbook_date', models.DateField(verbose_name='Last Read Book Date')),
                ('count_date', models.IntegerField(default=0, verbose_name='Count Date')),
            ],
            options={
                'verbose_name': 'Times Read Book',
            },
        ),
    ]
