# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badge', '0001_initial'),
        ('kid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesreadbook',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_readbook_kids_rel', to='kid.Kid'),
        ),
        migrations.AddField(
            model_name='kidbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kidbadges_badges_rel', to='badge.Badge'),
        ),
        migrations.AddField(
            model_name='kidbadge',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kidbadges_kids_rel', to='kid.Kid'),
        ),
    ]
