# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badge', '0002_auto_20181130_1544'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_badge_created_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='badge',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_badge_modified_by', to='staff.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='kidbadge',
            unique_together=set([('badge', 'kid')]),
        ),
    ]
