# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decription')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('effective_time', models.IntegerField(default=0, verbose_name='Effective Time')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Trial')),
                ('kid_limit', models.IntegerField(default=3, verbose_name='Kid Limit')),
                ('status', django_fsm.FSMField(default='draft', max_length=50)),
            ],
            options={
                'verbose_name': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackagePersonalBookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookCategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Package')),
            ],
            options={
                'verbose_name': 'Package Personal Book Category',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('personal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal id')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Personal/Avatar', verbose_name='Avatar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_personal_created_by', to='staff.Staff')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_personal_modified_by', to='staff.Staff')),
            ],
            options={
                'verbose_name': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='PersonalPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Package')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
            options={
                'verbose_name': 'Personal Package',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='packages',
            field=models.ManyToManyField(blank=True, through='personal.PersonalPackage', to='personal.Package'),
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_personal_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='book_categories',
            field=models.ManyToManyField(blank=True, related_name='rel_package_personal_m2m_book_category', through='personal.PackagePersonalBookCategory', to='core.BookCategory'),
        ),
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_package_created_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='package',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_package_modified_by', to='staff.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='packagepersonalbookcategory',
            unique_together=set([('package', 'book_category')]),
        ),
    ]
