# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Book Favourite',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
            ],
            options={
                'verbose_name': 'Book Mark',
            },
        ),
        migrations.CreateModel(
            name='InvitedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Invited Book',
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nick Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('phone', models.CharField(max_length=50, null=True, unique=True, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True, verbose_name='Gender')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Kid/Avatar', verbose_name='Avatar')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
        ),
        migrations.CreateModel(
            name='KidReadBookTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('done', 'Done')], default='reading', max_length=50, verbose_name='Status')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Page Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KidStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Kid Store',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('point', models.IntegerField(verbose_name='Point')),
                ('image', models.ImageField(upload_to='Store', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
