# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('kid', '0001_initial'),
        ('staff', '0001_initial'),
        ('personal', '0001_initial'),
        ('core', '0002_auto_20181130_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kid_store_created_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='store',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kid_store_modified_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='kidstore',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid'),
        ),
        migrations.AddField(
            model_name='kidstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Store'),
        ),
        migrations.AddField(
            model_name='kidreadbooktrack',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
        migrations.AddField(
            model_name='kidreadbooktrack',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid'),
        ),
        migrations.AddField(
            model_name='kid',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_organization_rel', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='kid',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_personal_rel', to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='invitedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
        migrations.AddField(
            model_name='invitedbook',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid'),
        ),
        migrations.AddField(
            model_name='invitedbook',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='invitedbook',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid'),
        ),
        migrations.AddField(
            model_name='bookfavourite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
        migrations.AddField(
            model_name='bookfavourite',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.Kid'),
        ),
        migrations.AlterUniqueTogether(
            name='kidstore',
            unique_together=set([('store', 'kid')]),
        ),
        migrations.AlterUniqueTogether(
            name='invitedbook',
            unique_together=set([('book', 'kid', 'teacher'), ('book', 'kid', 'personal')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('book', 'kid', 'page_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookfavourite',
            unique_together=set([('book', 'kid')]),
        ),
    ]
