# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransactionTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Cancel'), ('error', 'Error'), ('done', 'Done')], default='pending', max_length=250, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateway_personaltransactiontrack_created_by', to='staff.Staff')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateway_personaltransactiontrack_modified_by', to='staff.Staff')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Package')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
